language: node_js
node_js:
  - "7"
before_install:
- openssl aes-256-cbc -K $encrypted_68b39119197e_key -iv $encrypted_68b39119197e_iv
  -in deploy/deploy_key.enc -out deploy/deploy_key -d
deploy:
  provider: script
  script: deploy/deploy.sh
  on:
    branch: master
